name: build

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'     
        required: true

jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: ubuntu-24.04
    #needs: setup
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v6
      - name: Create a new release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ inputs.version }} 
        run: |
          gh release create \
            --target ${{ inputs.version }} \
            --title "Version ${{ inputs.version }}" \
            --notes "Produced by GitHub actions run: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}" \
            ${{ inputs.version }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      #- name: Install rust
      #  run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install cross (from git revision 65fe72b)
        #run: . "$HOME/.cargo/env" && cargo install cross --git https://github.com/cross-rs/cross --rev 65fe72b
        run: cargo install cross --git https://github.com/cross-rs/cross --rev 65fe72b
      - name: Clone libsignal repository
        run: git clone --depth 1 --branch ${{ inputs.version }} https://github.com/signalapp/libsignal libsignal
      - name: Free up disk space
        run: |
          # Remove Java (JDKs)
          sudo rm -rf /usr/lib/jvm

          # Remove .NET SDKs
          sudo rm -rf /usr/share/dotnet

          # Remove Swift toolchain
          sudo rm -rf /usr/share/swift

          # Remove Haskell (GHC)
          sudo rm -rf /usr/local/.ghcup

          # Remove Julia
          sudo rm -rf /usr/local/julia*

          # Remove Android SDKs
          sudo rm -rf /usr/local/lib/android

          # Remove Chromium
          sudo rm -rf /usr/local/share/chromium

          # Remove Microsoft/Edge and Google Chrome builds
          sudo rm -rf /opt/microsoft /opt/google

          # Remove Azure CLI
          sudo rm -rf /opt/az

          # Remove PowerShell
          sudo rm -rf /usr/local/share/powershell

          # Remove CodeQL and other toolcaches
          #sudo rm -rf /opt/hostedtoolcache

          #docker system prune -af || true
          #docker builder prune -af || true
          df -h
      - name: Copy Cross.toml to libsignal folder
        run: cp Cross.toml libsignal/
      - name: Enable multi-architecture builds
        run: docker run --privileged --rm tonistiigi/binfmt --install all
      - name: Create artifacts directory
        run: mkdir -p $GITHUB_WORKSPACE/assets && mkdir -p $GITHUB_WORKSPACE/assets/x86-64 && mkdir -p $GITHUB_WORKSPACE/assets/armv7 && mkdir -p $GITHUB_WORKSPACE/assets/arm64
      - name: Build for x86-64
        run: |
          df -h
          echo "Change into libsignal directory"
          cd $GITHUB_WORKSPACE/libsignal
          rm -rf target
          echo "Start build"
          /home/runner/.cargo/bin/cross build --target x86_64-unknown-linux-gnu --release -p libsignal-jni
          cp target/x86_64-unknown-linux-gnu/release/libsignal_jni.so $GITHUB_WORKSPACE/assets/x86-64
      - name: Build for armv7
        run: |
          df -h
          echo "Change into libsignal directory"
          cd $GITHUB_WORKSPACE/libsignal
          rm -rf target
          echo "Start build"
          /home/runner/.cargo/bin/cross build --target armv7-unknown-linux-gnueabihf --release -p libsignal-jni
          cp target/armv7-unknown-linux-gnueabihf/release/libsignal_jni.so $GITHUB_WORKSPACE/assets/armv7
      - name: Build for arm64
        run: |
          df -h
          echo "Change into libsignal directory"
          cd $GITHUB_WORKSPACE/libsignal
          rm -rf target
          echo "Start build"
          /home/runner/.cargo/bin/cross build --target aarch64-unknown-linux-gnu --release -p libsignal-jni
          cp target/aarch64-unknown-linux-gnu/release/libsignal_jni.so $GITHUB_WORKSPACE/assets/arm64
      - name: Create archive
        run: cd $GITHUB_WORKSPACE/assets && tar -czvf libsignal-client-build-${{ inputs.version }}.tar.gz .
      - name: Upload release asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ inputs.version }}
        run: gh release upload "$TAG_NAME" "${GITHUB_WORKSPACE}/assets/libsignal-client-build-${TAG_NAME}.tar.gz"
